### ISSUE TITLE
[BUG] Exception reported: Invalid data pack type (got 3 / expected 1).

### ISSUE THREAD

**Issue by justaFluffypanda** [totles/z4lab-surftimer#98] opened 2019-11-21 19:41 UTC
L 11/21/2019 - 13:46:04: [SM] Exception reported: Invalid data pack type (got 3 / expected 1).
L 11/21/2019 - 13:46:04: [SM] Blaming: SurfTimer.smx
L 11/21/2019 - 13:46:04: [SM] Call stack trace:
L 11/21/2019 - 13:46:04: [SM]   [0] ReadPackCell
L 11/21/2019 - 13:46:04: [SM]   [1] Line 2063, surftimer/sql.sp::sql_selectTopSurfersCallback

SM 1.10 build 6455

**Comment by justaFluffypanda** [comment] 2019-11-21 19:48
Probably related: https://github.com/alliedmodders/sourcemod/pull/688

**Comment by 13ace37** [comment] 2019-11-21 19:57
Try to remove or change all empty names in the `ck_playerrank` and `ck_playertimes` tables.

```SQL
UPDATE `surftimer`.`ck_playertimes` SET `name` = 'N/A' WHERE `name` = '';
```
```SQL
UPDATE `surftimer`.`ck_playerrank` SET `name` = 'N/A' WHERE `name` = ''
```

And how is your timer even working? In the current state of the master the timer won't even load with SM 1.10 🤔

**Comment by justaFluffypanda** [comment] 2019-11-21 20:11
I'm not sure, it's definitely working though.  I updated from fluffys branch earlier this week after the shattered web update and at the same time updated to SM 1.10 (6455).  The only things I've changed for the surftimer plugin is the formatting in misc.sp to remove HUD color as per [this comment](https://github.com/totles/z4lab-surftimer/issues/95#issuecomment-555653845), the database character set in sql.sp to utf8mb4, and the sql_selectMapRecord query in queries.sp.

**Comment by justaFluffypanda** [comment] 2019-11-21 20:12
Also, will make database changes as suggested and report back...

**Comment by 13ace37** [comment] 2019-11-21 20:14
I see. For me, it wasn't working using 1.10 - it just crashed the server if someone joined it. 
And btw you could use the 280pre release or if you want to want to compile it your self https://github.com/totles/z4lab-surftimer/tree/dev .

**Comment by justaFluffypanda** [comment] 2019-11-21 20:23
Hmm sourcemod dev build required, I do like living on the edge

**Comment by 13ace37** [comment] 2019-11-21 20:24
If the current one is working for you, it's probably working with 1.10 too.

**Comment by justaFluffypanda** [comment] 2019-11-21 20:26
Cool, I'll build it tomorrow for one of my servers and see.

**Comment by 13ace37** [comment] 2019-11-21 22:15
It's working for me at 1.10 too. LinuxGSM still used 1.9 :)

**Comment by Marfimm** [comment] 2019-11-26 13:24
I have the same problem, I tried to do what @13ace37 suggested, but it didn't work, !mtop is broken 😕

**Comment by justaFluffypanda** [comment] 2019-11-26 18:17
@Marfimm Can confirm, I applied the suggestion from @13ace37 but still have these in my error logs

L 11/25/2019 - 23:52:24: [SM] Exception reported: Client 12 is not connected
L 11/25/2019 - 23:52:24: [SM] Blaming: SurfTimer.smx
L 11/25/2019 - 23:52:24: [SM] Call stack trace:
L 11/25/2019 - 23:52:24: [SM]   [0] GetClientName
L 11/25/2019 - 23:52:24: [SM]   [1] Line 5999, surftimer/sql.sp::SQL_UpdateWrcpRecordCallback2

L 11/25/2019 - 22:39:11: [SM] Exception reported: Invalid data pack type (got 3 / expected 1).
L 11/25/2019 - 22:39:11: [SM] Blaming: SurfTimer.smx
L 11/25/2019 - 22:39:11: [SM] Call stack trace:
L 11/25/2019 - 22:39:11: [SM]   [0] ReadPackCell
L 11/25/2019 - 22:39:11: [SM]   [1] Line 2063, surftimer/sql.sp::sql_selectTopSurfersCallback

**Comment by 13ace37** [comment] 2019-12-17 16:33
> L 11/25/2019 - 23:52:24: [SM] Exception reported: Client 12 is not connected
L 11/25/2019 - 23:52:24: [SM] Blaming: SurfTimer.smx
L 11/25/2019 - 23:52:24: [SM] Call stack trace:
L 11/25/2019 - 23:52:24: [SM] [0] GetClientName
L 11/25/2019 - 23:52:24: [SM] [1] Line 5999, surftimer/sql.sp::SQL_UpdateWrcpRecordCallback2

That's something else. If this one appears in your logs again, please open a new issue.

>L 11/25/2019 - 22:39:11: [SM] Exception reported: Invalid data pack type (got 3 / expected 1).
L 11/25/2019 - 22:39:11: [SM] Blaming: SurfTimer.smx
L 11/25/2019 - 22:39:11: [SM] Call stack trace:
L 11/25/2019 - 22:39:11: [SM] [0] ReadPackCell
L 11/25/2019 - 22:39:11: [SM] [1] Line 2063, surftimer/sql.sp::sql_selectTopSurfersCallback

And this one happens if either no client name is provided into the database (non-supported names like invisible steam names etc. `𐂃𐂃`, `　`, ` ุ `) or the client had/has a non-unicode/utf8 name like `c̴̡͈̹͈̥̗͆̐̅̐̑̃̊̈́̔̚ḻ̷̨̢̧͊͋͂́̓̊̽i̵̞͕͈̟͚̘͐͋̏̎̆̋́è̸̯̩̳͕̪͕̼̓́́͗̊̔́́ͅn̷̝̖̫̜͓̓̈́̀̑͑͌̈̒̈́ͅt̴͎̪̫̩͈͝͠ ̸͚͔̦͖̖̟̈͌̄̔̽n̷͙̖̱̩̙̲͇̖̩̝̉̀͋̀̀a̶͖̜̮͎͓͎̮̱͐̋m̵̫̖̄̇̿͊̂̚é̸͕̥̫̤̘̰̳̜̺͛̏̇`, `ƈʅιҽɳƚ ɳαɱҽ`, `ᑕᒪIEᑎT ᑎᗩᗰE`

I'm pretty sure I've seen a plugin for this one. I'll comment bellow if I'm able to find it.

**Comment by 13ace37** [comment] 2020-01-06 02:04
Small Update: 
This should be fixed with https://github.com/totles/z4lab-surftimer/commit/6754f790aab641eedf7219ea3028a0ade9ece8f8 but I'm not 100% sure about it. 

After changing the client name charsets from `utf8` to `utf8m4` all not supported chars should be replaced with an `?`. https://github.com/totles/z4lab-surftimer/commit/6754f790aab641eedf7219ea3028a0ade9ece8f8#diff-4da42d77731162deed43af9163811bdeR43-R44

It works for our servers so far. I won't close this until I can confirm it 100%. 

I'll not release this since the next (281) update.

**Comment by 13ace37** [comment] 2020-01-31 17:58
Working fine for me now. Open another issue if the error shows up again.

**Comment by Z-RAY-Z** [comment] 2020-02-26 15:21
L 02/26/2020 - 18:19:11: [SM] Exception reported: Invalid data pack type (got 3 / expected 1).
L 02/26/2020 - 18:19:11: [SM] Blaming: surftimer_z4lab_280pre.smx
L 02/26/2020 - 18:19:11: [SM] Call stack trace:
L 02/26/2020 - 18:19:11: [SM]   [0] ReadPackCell
L 02/26/2020 - 18:19:11: [SM]   [1] Line 2061, surftimer/sql.sp::sql_selectTopSurfersCallback

SourceMod (1.10.0.6472) and stock SurfTimer (280)

**Comment by 13ace37** [comment] 2020-02-26 15:27
self compile the dev branch

**Comment by olokos** [comment] 2020-04-06 02:49
The issue was closed by an accident.
Oddly enough even if the table has no names that are empty this bug still occurs. 
Will investigate.

**Comment by olokos** [comment] 2020-04-06 19:31
@13ace37 has introduced a workaround for this bug
https://github.com/z4lab/z4lab-surftimer/commit/b1780ae7339ce3894a640cd11e3705aa004e7953

**Comment by olokos** [comment] 2020-04-07 20:24
Workaround confirmed working.

**Closed as completed** 2020-04-09 19:21 UTC
Labels: testing
